baseURL: http://techmyth.github.io/
languageCode: en-us
copyright: "2022 Jonathan Colon All rights reserved"
title: TechMyth
theme: "PaperMod"

enableRobotsTXT: true


author:
  name: Jonathan Colon

DefaultContentLanguage: "en"

googleAnalytics: G-H243NQ4V8N

sitemap:
  changefreq: weeklypr
  filename: sitemap.xml
  priority: 0.5

languages:
  es:
    languageName: Spanish
    homeInfoParams:
      Title: "Bienvenido al blog de Jonathan Col贸n "
      Content: "Investigador en Ciberseguridad, Desarrollador y experto en Infraestructura con intereses en Automatizaci贸n, DevOps, Redes, Sistemas basados en Multi-OS, Python, Golang, Powershell y apasionado por la contribuci贸n Open Source; amante de la L铆nea de Comandos, FOSS."
    menu:
      main:
      - identifier: home
        name: Inicio
        pre: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="22" viewBox="0 0 28 16" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 10v11h6v-7h6v7h6v-11L12,3z"></path></svg>
        params:
          class: highlight-menu-item
        url: /
        weight: 1
      # - identifier: posts
      #   name: Publicaciones
      #   pre: <svg xmlns="http://www.w3.org/2000/svg" width="28" height="18" fill="currentColor" class="bi bi-clipboard-pulse" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M10 1.5a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-1Zm-5 0A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5v1A1.5 1.5 0 0 1 9.5 4h-3A1.5 1.5 0 0 1 5 2.5v-1Zm-2 0h1v1H3a1 1 0 0 0-1 1V14a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V3.5a1 1 0 0 0-1-1h-1v-1h1a2 2 0 0 1 2 2V14a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V3.5a2 2 0 0 1 2-2Zm6.979 3.856a.5.5 0 0 0-.968.04L7.92 10.49l-.94-3.135a.5.5 0 0 0-.895-.133L4.232 10H3.5a.5.5 0 0 0 0 1h1a.5.5 0 0 0 .416-.223l1.41-2.115 1.195 3.982a.5.5 0 0 0 .968-.04L9.58 7.51l.94 3.135A.5.5 0 0 0 11 11h1.5a.5.5 0 0 0 0-1h-1.128L9.979 5.356Z"/></svg>
      #   params:
      #     class: highlight-menu-item
      #   url: /posts
      #   weight: 2
      - identifier: projects
        name: Proyectos
        pre: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="20" viewBox="0 0 28 16" fill="none" stroke="currentColor" stroke-width="1.1"><path d="M23 12l-7.071 7.071-1.414-1.414L20.172 12l-5.657-5.657 1.414-1.414L23 12zM3.828 12l5.657 5.657-1.414 1.414L1 12l7.071-7.071 1.414 1.414L3.828 12z"></path></svg>
        params:
          class: highlight-menu-item
        url: /projects
        weight: 3
      - identifier: about
        name: Sobre m铆
        pre: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="20" viewBox="0 0 28 16" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="none"><circle cx="12" cy="8" r="5" /><path d="M3,21 h18 C 21,12 3,12 3,21"/></svg>
        params:
          class: highlight-menu-item
        url: /about
        weight: 4
      # - identifier: search
      #   name: Busqueda
      #   params:
      #     class: highlight-menu-item
      #   url: search
      #   weight: 5
    title: TechMyth
    weight: 2
  en:
    languageName: English
    homeInfoParams:
      Title: "Welcome to Jonathan Col贸n's blog "
      Content: "Cyber-Security Researcher, Developer and Infrastructure expert having interests in Automation, DevOps, Networking, Multi-OS based Systems, Python, Golang, Powershell and passionate for Open Source contribution; loves Command Line, FOSS."
    menu:
      main:
      - identifier: home
        name: Home
        pre: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="22" viewBox="0 0 28 16" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 10v11h6v-7h6v7h6v-11L12,3z"></path></svg>
        params:
          class: highlight-menu-item
        url: /
        weight: 1
      # - identifier: posts
      #   name: Posts
      #   pre: <svg xmlns="http://www.w3.org/2000/svg" width="28" height="18" fill="currentColor" class="bi bi-clipboard-pulse" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M10 1.5a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-1Zm-5 0A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5v1A1.5 1.5 0 0 1 9.5 4h-3A1.5 1.5 0 0 1 5 2.5v-1Zm-2 0h1v1H3a1 1 0 0 0-1 1V14a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V3.5a1 1 0 0 0-1-1h-1v-1h1a2 2 0 0 1 2 2V14a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V3.5a2 2 0 0 1 2-2Zm6.979 3.856a.5.5 0 0 0-.968.04L7.92 10.49l-.94-3.135a.5.5 0 0 0-.895-.133L4.232 10H3.5a.5.5 0 0 0 0 1h1a.5.5 0 0 0 .416-.223l1.41-2.115 1.195 3.982a.5.5 0 0 0 .968-.04L9.58 7.51l.94 3.135A.5.5 0 0 0 11 11h1.5a.5.5 0 0 0 0-1h-1.128L9.979 5.356Z"/></svg>
      #   params:
      #     class: highlight-menu-item
      #   url: /posts
      #   weight: 2
      - identifier: projects
        name: Projects
        pre: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="20" viewBox="0 0 28 16" fill="none" stroke="currentColor" stroke-width="1.1"><path d="M23 12l-7.071 7.071-1.414-1.414L20.172 12l-5.657-5.657 1.414-1.414L23 12zM3.828 12l5.657 5.657-1.414 1.414L1 12l7.071-7.071 1.414 1.414L3.828 12z"></path></svg>
        params:
          class: highlight-menu-item
        url: /projects
        weight: 3
      - identifier: about
        name: About me
        pre: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="20" viewBox="0 0 28 16" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="none"><circle cx="12" cy="8" r="5" /><path d="M3,21 h18 C 21,12 3,12 3,21"/></svg>
        params:
          class: highlight-menu-item
        url: /about
        weight: 4
      # - identifier: search
      #   name: Search
      #   params:
      #     class: highlight-menu-item
      #   url: /search
      #   weight: 5
    title: TechMyth
    weight: 1

params:
  env: production
  description: "System Engineer in pyjama"
  author: Jon Colon
  defaultTheme: auto
  disableThemeToggle: false
  ShowFullTextinRSS: true
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowWordCount: false
  disableSpecial1stPost: false
  socialIcons:
  - name: "email"
    url: "mailto:jcolonf@zenprsolutions.com"
  - name: "kofi"
    url: "https://ko-fi.com/F1F8DEV80"
  - name: "twitter"
    url: "https://twitter.com/jcolonfzenpr"
  - name: "rss"
    url: "https://techmyth.github.io/index.xml"
  - name: "linkedin"
    url: "https://www.linkedin.com/in/jcolonfzenpr/"
  - name: "github"
    url: "https://github.com/rebelinux"
  - name: "reddit"
    url: "https://www.reddit.com/user/jcolonfzenpr"
  - name: "cv"
    url: "https://rxresu.me/jcolonf/jonathan-colon-"
  label:
    text: "TechMyth"
    icon: /img/home_logo.webp
    iconHeight: 35
  editPost:
    URL: "https://github.com/techmyth/techmyth.github.io/tree/main/content"
    Text: "Suggest Changes"
    appendFilePath: true
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]


outputs:
  home:
      - HTML
      - RSS

markup:
  markup.goldmark:
    markup.goldmark.parser:
      wrapStandAloneImageWithinParagraph: false
      markup.goldmark.parser.attribute:
        block: true
